{
  "type": "issue",
  "issue": {
    "id": 258478806,
    "node_id": "MDU6SXNzdWUyNTg0Nzg4MDY=",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/11360",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/11360/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/11360/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/11360/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/11360",
    "number": 11360,
    "state": "closed",
    "state_reason": "completed",
    "title": "Error: Prune: last wallet synchronisation goes beyond pruned data",
    "body": "On startup, I get \"Error: Prune: last wallet synchronisation goes beyond pruned data. You need to -reindex (download the whole blockchain again in case of pruned node)\"\r\n\r\nAs noted below, this message seems wrong as I was able to restart w/o issues - didn't reindex or download the blockchain again.\r\n\r\nI am not asking for help with this. I just wanted to record this incident because #7494 was closed as fixed, but I ran into the same problem with 0.15.\r\n\r\n### Can you reliably reproduce the issue?\r\nNo.\r\n\r\n#### If so, please list the steps to reproduce below:\r\n1. Run 0.14.2 in pruned mode\r\n2. Stop/start/stop 0.14.2 several times\r\n3. Upgrade to 0.15\r\n3. Start 0.15\r\n\r\nI am *not* sure how I might reproduce this, but it's very much like this issue here:\r\nhttps://github.com/bitcoin/bitcoin/issues/7494#issue-132587553\r\n\r\nI *might* have had a power failure or rebooted the host without shutting down this VM, I don't remember now. Today is Sep 18; I see in .bitcoin/chainstate that it seems Sep 10 was the last time I ran, and before that in August. \r\nIt's possible that on Sep 10 I shut down the VM before it finished syncing which is one of possible reasons for this problem, mentioned in issue #7494. \r\n\r\n### What version of bitcoin-core are you using?\r\nv0.15.0 (official binary)\r\n\r\n### Machine specs:\r\n- OS: Ubuntu 16.04 LTS\r\n- CPU: i7\r\n- RAM: 16 G\r\n- Disk size: 200 G\r\n- Disk Type (HD/SDD): SSD\r\n\r\n### Any extra information that might be useful in the debugging process.\r\n\r\nI just restarted. I did delete .lock before that, but I don't think it mattered.\r\n\r\nNext time I started, there was no sign of any trouble. It doesn't look like Bitcoin had to completely resync .\r\nWallet seems to be working OK (I don't have any funds in it, but getbalance and such doesn't give any errors; I never used wallet so it's empty). \r\n\r\nFail log:\r\n\r\n```\r\n# tail -f .bitcoin/debug.log\r\n2017-09-18 12:58:57 init message: Loading block index...\r\n2017-09-18 12:58:57 Opening LevelDB in /root/.bitcoin/blocks/index\r\n2017-09-18 12:58:57 Opened LevelDB successfully\r\n2017-09-18 12:58:57 Using obfuscation key for /root/.bitcoin/blocks/index: 0000000000000000\r\n2017-09-18 12:59:00 LoadBlockIndexDB: last block file = 994\r\n2017-09-18 12:59:00 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=58, size=46642763, heights=483555...484527, time=2017-09-05...2017-09-10)\r\n2017-09-18 12:59:00 Checking all blk files are present...\r\n2017-09-18 12:59:00 LoadBlockIndexDB(): Block files have previously been pruned\r\n2017-09-18 12:59:00 LoadBlockIndexDB: transaction index disabled\r\n2017-09-18 12:59:00 Opening LevelDB in /root/.bitcoin/chainstate\r\n2017-09-18 12:59:02 Opened LevelDB successfully\r\n2017-09-18 12:59:02 Using obfuscation key for /root/.bitcoin/chainstate: 268af1ce9bee0cb3\r\n2017-09-18 12:59:02 Loaded best chain: hashBestChain=0000000000000000011c5c5d5158781964fa1c62c76436a7c048f3b60bf767ce height=484527 date=2017-09-10 15:00:52 progress=0.991703\r\n2017-09-18 12:59:02 init message: Rewinding blocks...\r\n2017-09-18 12:59:03 init message: Verifying blocks...\r\n2017-09-18 12:59:03 Verifying last 6 blocks at level 3\r\n2017-09-18 12:59:03 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].\r\n2017-09-18 12:59:08 No coin database inconsistencies in last 7 blocks (8434 transactions)\r\n2017-09-18 12:59:08  block index           10261ms\r\n2017-09-18 12:59:08 init message: Loading wallet...\r\n2017-09-18 12:59:08 nFileVersion = 140100\r\n2017-09-18 12:59:08 Keys: 102 plaintext, 0 encrypted, 102 w/ metadata, 102 total\r\n2017-09-18 12:59:08  wallet                    6ms\r\n2017-09-18 12:59:08 keypool added 900 keys (0 internal), size=1000 (0 internal)\r\n2017-09-18 12:59:08 Error: Prune: last wallet synchronisation goes beyond pruned data. You need to -reindex (download the whole blockchain again in case of pruned node)\r\n2017-09-18 12:59:08 scheduler thread interrupt\r\n2017-09-18 12:59:08 Shutdown: In progress...\r\n2017-09-18 12:59:08 Shutdown: done\r\n2017-09-18 12:59:08 CDBEnv::EnvShutdown: Error 22 shutting down database environment: Invalid argument\r\n^C\r\n```\r\n\r\nAfter that I checked db.log:\r\n\r\n```\r\n# cat db.log\r\nDatabase handles still open at environment close\r\nOpen database handle: wallet.dat/main\r\n```\r\n\r\n",
    "user": {
      "login": "unsystemizer",
      "id": 13134193,
      "node_id": "MDQ6VXNlcjEzMTM0MTkz",
      "avatar_url": "https://avatars.githubusercontent.com/u/13134193?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/unsystemizer",
      "html_url": "https://github.com/unsystemizer",
      "followers_url": "https://api.github.com/users/unsystemizer/followers",
      "following_url": "https://api.github.com/users/unsystemizer/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/unsystemizer/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/unsystemizer/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/unsystemizer/subscriptions",
      "organizations_url": "https://api.github.com/users/unsystemizer/orgs",
      "repos_url": "https://api.github.com/users/unsystemizer/repos",
      "events_url": "https://api.github.com/users/unsystemizer/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/unsystemizer/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "locked": true,
    "active_lock_reason": "resolved",
    "comments": 2,
    "closed_at": "2020-04-26T22:25:39Z",
    "created_at": "2017-09-18T13:26:34Z",
    "updated_at": "2022-08-18T18:34:17Z"
  },
  "events": [
    {
      "event": "commented",
      "id": 619634379,
      "node_id": "MDEyOklzc3VlQ29tbWVudDYxOTYzNDM3OQ==",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/619634379",
      "actor": {
        "login": "MarcoFalke",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarcoFalke",
        "html_url": "https://github.com/MarcoFalke",
        "followers_url": "https://api.github.com/users/MarcoFalke/followers",
        "following_url": "https://api.github.com/users/MarcoFalke/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/MarcoFalke/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/MarcoFalke/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
        "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
        "repos_url": "https://api.github.com/users/MarcoFalke/repos",
        "events_url": "https://api.github.com/users/MarcoFalke/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2020-04-26T22:25:39Z",
      "updated_at": "2020-04-26T22:25:39Z",
      "author_association": "MEMBER",
      "body": "Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?",
      "user": {
        "login": "MarcoFalke",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarcoFalke",
        "html_url": "https://github.com/MarcoFalke",
        "followers_url": "https://api.github.com/users/MarcoFalke/followers",
        "following_url": "https://api.github.com/users/MarcoFalke/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/MarcoFalke/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/MarcoFalke/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
        "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
        "repos_url": "https://api.github.com/users/MarcoFalke/repos",
        "events_url": "https://api.github.com/users/MarcoFalke/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/11360#issuecomment-619634379",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/11360"
    },
    {
      "event": "closed",
      "id": 3273444867,
      "node_id": "MDExOkNsb3NlZEV2ZW50MzI3MzQ0NDg2Nw==",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/3273444867",
      "actor": {
        "login": "MarcoFalke",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarcoFalke",
        "html_url": "https://github.com/MarcoFalke",
        "followers_url": "https://api.github.com/users/MarcoFalke/followers",
        "following_url": "https://api.github.com/users/MarcoFalke/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/MarcoFalke/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/MarcoFalke/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
        "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
        "repos_url": "https://api.github.com/users/MarcoFalke/repos",
        "events_url": "https://api.github.com/users/MarcoFalke/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2020-04-26T22:25:40Z"
    },
    {
      "event": "commented",
      "id": 780571187,
      "node_id": "MDEyOklzc3VlQ29tbWVudDc4MDU3MTE4Nw==",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/780571187",
      "actor": {
        "login": "Philomorph",
        "id": 13068591,
        "node_id": "MDQ6VXNlcjEzMDY4NTkx",
        "avatar_url": "https://avatars.githubusercontent.com/u/13068591?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Philomorph",
        "html_url": "https://github.com/Philomorph",
        "followers_url": "https://api.github.com/users/Philomorph/followers",
        "following_url": "https://api.github.com/users/Philomorph/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/Philomorph/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/Philomorph/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/Philomorph/subscriptions",
        "organizations_url": "https://api.github.com/users/Philomorph/orgs",
        "repos_url": "https://api.github.com/users/Philomorph/repos",
        "events_url": "https://api.github.com/users/Philomorph/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/Philomorph/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2021-02-17T13:53:58Z",
      "updated_at": "2021-02-17T13:53:58Z",
      "author_association": "NONE",
      "body": "I just got this error with the latest version of core (0.21.0).\r\nI haven't used BitCoin since 2017. I installed core last night and started downloading the blockchain overnight. I left the prune setting to the default 2Gb.\r\nWhen I woke up it was up to November 2017, and the date on my wallet file was October 2017, so I figured I'd load it up and see if it had anything in it.\r\nI closed the core client completely, copied the wallet file to the wallets folder, and restarted core.\r\nIt gave this error and then closed when I hit OK.\r\nI started core up again and it's acting normally, continuing to download. The wallet screen says balance info is out of date, but that's the only indication it's not caught up.\r\nI have another half a day probably for it to catch up - not sure what will happen when it does, but figured I'd report the error.",
      "user": {
        "login": "Philomorph",
        "id": 13068591,
        "node_id": "MDQ6VXNlcjEzMDY4NTkx",
        "avatar_url": "https://avatars.githubusercontent.com/u/13068591?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Philomorph",
        "html_url": "https://github.com/Philomorph",
        "followers_url": "https://api.github.com/users/Philomorph/followers",
        "following_url": "https://api.github.com/users/Philomorph/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/Philomorph/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/Philomorph/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/Philomorph/subscriptions",
        "organizations_url": "https://api.github.com/users/Philomorph/orgs",
        "repos_url": "https://api.github.com/users/Philomorph/repos",
        "events_url": "https://api.github.com/users/Philomorph/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/Philomorph/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/11360#issuecomment-780571187",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/11360"
    },
    {
      "event": "locked",
      "id": 7216598953,
      "node_id": "LOE_lADOABII584PaBLWzwAAAAGuJI-p",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/7216598953",
      "actor": {
        "login": "DrahtBot",
        "id": 39886733,
        "node_id": "MDQ6VXNlcjM5ODg2NzMz",
        "avatar_url": "https://avatars.githubusercontent.com/u/39886733?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/DrahtBot",
        "html_url": "https://github.com/DrahtBot",
        "followers_url": "https://api.github.com/users/DrahtBot/followers",
        "following_url": "https://api.github.com/users/DrahtBot/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/DrahtBot/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/DrahtBot/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/DrahtBot/subscriptions",
        "organizations_url": "https://api.github.com/users/DrahtBot/orgs",
        "repos_url": "https://api.github.com/users/DrahtBot/repos",
        "events_url": "https://api.github.com/users/DrahtBot/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/DrahtBot/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-08-18T18:34:17Z",
      "lock_reason": "resolved"
    }
  ]
}