{
  "type": "issue",
  "issue": {
    "id": 351924265,
    "node_id": "MDU6SXNzdWUzNTE5MjQyNjU=",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14004",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14004/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14004/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14004/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/14004",
    "number": 14004,
    "state": "closed",
    "state_reason": "completed",
    "title": "Failed IBD after block file blk00057.dat",
    "body": "<!-- Describe the issue -->\r\n<!--- What behavior did you expect? -->\r\n**Expected behaviour:** IBD without issues. Using 3.5\" WD Blue HDD (500GB) attached to Laptop via SATA to USB 3 adapter. CPU is at 20% max.\r\n\r\n<!--- What was the actual behavior (provide screenshots if the issue is GUI-related)? -->\r\n**Actual behaviour:** After around 4.78% / block file blk00057.dat in the `blocks/` folder, it fails with the following error in `debug.log`:\r\n`LevelDB read failure: Corruption: block checksum mismatch`\r\n\r\n<!-- What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)? -->\r\nThis happens both on Bitcoin Core 0.16.1 and 0.16.2\r\n\r\n<!-- What type of machine are you observing the error on (OS/CPU and disk type)? -->\r\nMachine: MacBook Pro, macOS 10.13\r\n\r\n<!-- Any extra information that might be useful in the debugging process. -->\r\n<!--- This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred. -->\r\nOutput from debug.log:\r\n2018-08-19 18:20:56 LevelDB read failure: Corruption: block checksum mismatch: /Volumes/WD500/Bitcoin/chainstate/000466.ldb\r\n2018-08-19 18:20:56 Corruption: block checksum mismatch: /Volumes/WD500/Bitcoin/chainstate/000466.ldb\r\n2018-08-19 18:21:17 Error reading from database: Database corrupted\r\n\r\n**Regarding the HDD health:**\r\nI've run `smartctl --test long` and the output was: \r\n\r\nSMART Self-test log structure revision number 1\r\nNum  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error\r\n\\# 1  Extended offline    Completed without error       00%      2160         -",
    "user": {
      "login": "unixb0y",
      "id": 6874233,
      "node_id": "MDQ6VXNlcjY4NzQyMzM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6874233?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/unixb0y",
      "html_url": "https://github.com/unixb0y",
      "followers_url": "https://api.github.com/users/unixb0y/followers",
      "following_url": "https://api.github.com/users/unixb0y/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/unixb0y/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/unixb0y/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/unixb0y/subscriptions",
      "organizations_url": "https://api.github.com/users/unixb0y/orgs",
      "repos_url": "https://api.github.com/users/unixb0y/repos",
      "events_url": "https://api.github.com/users/unixb0y/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/unixb0y/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "assignees": [],
    "author_association": "NONE",
    "locked": true,
    "active_lock_reason": "resolved",
    "comments": 1,
    "closed_at": "2018-08-22T22:18:17Z",
    "created_at": "2018-08-19T18:36:41Z",
    "updated_at": "2021-09-08T12:38:42Z"
  },
  "events": [
    {
      "event": "commented",
      "id": 415200182,
      "node_id": "MDEyOklzc3VlQ29tbWVudDQxNTIwMDE4Mg==",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/415200182",
      "actor": {
        "login": "unixb0y",
        "id": 6874233,
        "node_id": "MDQ6VXNlcjY4NzQyMzM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6874233?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/unixb0y",
        "html_url": "https://github.com/unixb0y",
        "followers_url": "https://api.github.com/users/unixb0y/followers",
        "following_url": "https://api.github.com/users/unixb0y/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/unixb0y/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/unixb0y/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/unixb0y/subscriptions",
        "organizations_url": "https://api.github.com/users/unixb0y/orgs",
        "repos_url": "https://api.github.com/users/unixb0y/repos",
        "events_url": "https://api.github.com/users/unixb0y/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/unixb0y/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2018-08-22T22:18:17Z",
      "updated_at": "2018-08-22T22:18:17Z",
      "author_association": "NONE",
      "body": "I have a little update regarding this issue. \r\nAfter too much time trying different stuff, I went the easy way, formatted the disk to NTFS and retried on a Windows machine. Everything looking fine, but we'll see about Linux drivers for NTFS once the download is finished.  \r\nI'm not sure, but it might be very possible that the Paragon extFS driver caused the issue. I wanted to have the drive be ext4 so the Raspberry Pi that I'm going to use later (to have the node always online) won't have any issues. This meant that I had to install this 3rd party driver for the Mac.\r\nSo everybody trying to setup a HDD for a Linux system on a Mac, maybe do a dual-boot or something like that to prevent this issue.",
      "user": {
        "login": "unixb0y",
        "id": 6874233,
        "node_id": "MDQ6VXNlcjY4NzQyMzM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6874233?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/unixb0y",
        "html_url": "https://github.com/unixb0y",
        "followers_url": "https://api.github.com/users/unixb0y/followers",
        "following_url": "https://api.github.com/users/unixb0y/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/unixb0y/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/unixb0y/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/unixb0y/subscriptions",
        "organizations_url": "https://api.github.com/users/unixb0y/orgs",
        "repos_url": "https://api.github.com/users/unixb0y/repos",
        "events_url": "https://api.github.com/users/unixb0y/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/unixb0y/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/14004#issuecomment-415200182",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/14004"
    },
    {
      "event": "closed",
      "id": 1803850850,
      "node_id": "MDExOkNsb3NlZEV2ZW50MTgwMzg1MDg1MA==",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/1803850850",
      "actor": {
        "login": "unixb0y",
        "id": 6874233,
        "node_id": "MDQ6VXNlcjY4NzQyMzM=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6874233?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/unixb0y",
        "html_url": "https://github.com/unixb0y",
        "followers_url": "https://api.github.com/users/unixb0y/followers",
        "following_url": "https://api.github.com/users/unixb0y/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/unixb0y/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/unixb0y/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/unixb0y/subscriptions",
        "organizations_url": "https://api.github.com/users/unixb0y/orgs",
        "repos_url": "https://api.github.com/users/unixb0y/repos",
        "events_url": "https://api.github.com/users/unixb0y/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/unixb0y/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2018-08-22T22:18:17Z"
    },
    {
      "event": "locked",
      "id": 5272036274,
      "node_id": "LOE_lADOABII584U-fApzwAAAAE6POOy",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/5272036274",
      "actor": {
        "login": "DrahtBot",
        "id": 39886733,
        "node_id": "MDQ6VXNlcjM5ODg2NzMz",
        "avatar_url": "https://avatars.githubusercontent.com/u/39886733?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/DrahtBot",
        "html_url": "https://github.com/DrahtBot",
        "followers_url": "https://api.github.com/users/DrahtBot/followers",
        "following_url": "https://api.github.com/users/DrahtBot/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/DrahtBot/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/DrahtBot/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/DrahtBot/subscriptions",
        "organizations_url": "https://api.github.com/users/DrahtBot/orgs",
        "repos_url": "https://api.github.com/users/DrahtBot/repos",
        "events_url": "https://api.github.com/users/DrahtBot/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/DrahtBot/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2021-09-08T12:38:42Z",
      "lock_reason": "resolved"
    }
  ]
}