{
  "type": "issue",
  "issue": {
    "id": 1272988209,
    "node_id": "I_kwDOABII585L4EIx",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/25385",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/25385/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/25385/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/25385/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/25385",
    "number": 25385,
    "state": "closed",
    "state_reason": "completed",
    "title": "Reproducible Test Failures",
    "body": "I've been having issues performing tests on PRs, so I've tried it multiple times now on master, deleting the directory and starting fresh. This is what I get each time:\r\n\r\n`make`\r\n\r\n> ...\r\n> ...\r\n> AR       minisketch/libminisketch_clmul.a\r\n>   CXXLD    test/test_bitcoin\r\n> collect2: fatal error: ld terminated with signal 9 [Killed]\r\n> compilation terminated.\r\n> make[2]: *** [Makefile:7539: test/test_bitcoin] Error 1\r\n> make[2]: Leaving directory '/home/user/bitcoin/src'\r\n> make[1]: *** [Makefile:18626: all-recursive] Error 1\r\n> make[1]: Leaving directory '/home/user/bitcoin/src'\r\n> make: *** [Makefile:818: all-recursive] Error 1\r\n\r\n`make` a second time, successful\r\n\r\n> ...\r\n> ...\r\n> CXX      util/libbitcoinconsensus_la-strencodings.lo\r\n>   CXXLD    libbitcoinconsensus.la\r\n> make[2]: Leaving directory '/home/user/bitcoin/src'\r\n> make[1]: Leaving directory '/home/user/bitcoin/src'\r\n> Making all in doc/man\r\n> make[1]: Entering directory '/home/user/bitcoin/doc/man'\r\n> make[1]: Nothing to be done for 'all'.\r\n> make[1]: Leaving directory '/home/user/bitcoin/doc/man'\r\n> make[1]: Entering directory '/home/user/bitcoin'\r\n> make[1]: Nothing to be done for 'all-am'.\r\n> make[1]: Leaving directory '/home/user/bitcoin'\r\n\r\nuser@localhost:~/bitcoin$ `make check`\r\n\r\n>  Making check in src\r\n> make[1]: Entering directory '/home/user/bitcoin/src'\r\n> make[2]: Entering directory '/home/user/bitcoin/src'\r\n> make[3]: Entering directory '/home/user/bitcoin'\r\n> make[3]: Leaving directory '/home/user/bitcoin'\r\n> make  check-TESTS check-local\r\n> make[3]: Entering directory '/home/user/bitcoin/src'\r\n> make[4]: Entering directory '/home/user/bitcoin/src'\r\n> PASS: minisketch/test\r\n> PASS: univalue/test/object\r\n> PASS: univalue/test/unitester\r\n> PASS: univalue/test/no_nul\r\n> make[5]: Entering directory '/home/user/bitcoin'\r\n> make[5]: Leaving directory '/home/user/bitcoin'\r\n> PASS: qt/test/test_bitcoin-qt\r\n> Testsuite summary for Bitcoin Core 23.99.0\r\n> '# TOTAL: 5\r\n> '# PASS:  5\r\n> '# SKIP:  0\r\n> '# XFAIL: 0\r\n> '# FAIL:  0\r\n> '# XPASS: 0\r\n> '# ERROR: 0\r\n> make[4]: Leaving directory '/home/user/bitcoin/src'\r\n> Running tests: addrman_tests from test/addrman_tests.cpp\r\n> /bin/bash: line 2: test/test_bitcoin: Permission denied\r\n> make[3]: *** [Makefile:20866: test/addrman_tests.cpp.test] Error 1\r\n> make[3]: Leaving directory '/home/user/bitcoin/src'\r\n> make[2]: *** [Makefile:18969: check-am] Error 2\r\n> make[2]: Leaving directory '/home/user/bitcoin/src'\r\n> make[1]: *** [Makefile:18626: check-recursive] Error 1\r\n> make[1]: Leaving directory '/home/user/bitcoin/src'\r\n> make: *** [Makefile:818: check-recursive] Error 1\r\n\r\nErrors also.\r\n\r\nuser@localhost:~/bitcoin$ `sudo make install`\r\n\r\n(No issues).\r\n\r\nuser@localhost:~/bitcoin/test/functional$ `python3 test_runner.py --extended`\r\n\r\n> feature_block.py                                   | ✖ Failed  | 83 s\r\n> feature_dbcrash.py                                 | ✖ Failed  | 2812 s\r\n> feature_pruning.py                                 | ✖ Failed  | 582 s\r\n\r\nDetails for each failed test:\r\n\r\n> 9/245 - feature_block.py failed, Duration: 83 s \r\n\r\n> stdout:\r\n> 2022-06-16T00:32:59.996000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20220615_202813/feature_block_235\r\n> 2022-06-16T00:33:02.154000Z TestFramework (INFO): Reject block with invalid tx: OutputMissing\r\n> 2022-06-16T00:33:02.380000Z TestFramework (INFO): Reject block with invalid tx: InputMissing\r\n> 2022-06-16T00:33:02.587000Z TestFramework (INFO): Reject block with invalid tx: BadInputOutpointIndex\r\n> 2022-06-16T00:33:02.800000Z TestFramework (INFO): Reject block with invalid tx: DuplicateInput\r\n> 2022-06-16T00:33:03.025000Z TestFramework (INFO): Reject block with invalid tx: PrevoutNullInput\r\n> 2022-06-16T00:33:03.195000Z TestFramework (INFO): Reject block with invalid tx: NonexistentInput\r\n> 2022-06-16T00:33:03.411000Z TestFramework (INFO): Reject block with invalid tx: SpendTooMuch\r\n> 2022-06-16T00:33:03.593000Z TestFramework (INFO): Reject block with invalid tx: CreateNegative\r\n> 2022-06-16T00:33:03.769000Z TestFramework (INFO): Reject block with invalid tx: CreateTooLarge\r\n> 2022-06-16T00:33:03.980000Z TestFramework (INFO): Reject block with invalid tx: CreateSumTooLarge\r\n> 2022-06-16T00:33:04.192000Z TestFramework (INFO): Reject block with invalid tx: TooManySigops\r\n> 2022-06-16T00:33:04.464000Z TestFramework (INFO): Don't reorg to a chain of the same length\r\n> 2022-06-16T00:33:04.571000Z TestFramework (INFO): Reorg to a longer chain\r\n> 2022-06-16T00:33:04.724000Z TestFramework (INFO): Reorg back to the original chain\r\n> 2022-06-16T00:33:05.109000Z TestFramework (INFO): Reject a chain with a double spend, even if it is longer\r\n> 2022-06-16T00:33:05.454000Z TestFramework (INFO): Reject a block where the miner creates too much coinbase reward\r\n> 2022-06-16T00:33:05.665000Z TestFramework (INFO): Reject a chain where the miner creates too much coinbase reward, even if the chain is longer\r\n> 2022-06-16T00:33:06.023000Z TestFramework (INFO): Reject a chain where the miner creates too much coinbase reward, even if the chain is longer (on a forked chain)\r\n> 2022-06-16T00:33:06.314000Z TestFramework (INFO): Accept a block with lots of checksigs\r\n> 2022-06-16T00:33:06.442000Z TestFramework (INFO): Reject a block with too many checksigs\r\n> 2022-06-16T00:33:06.698000Z TestFramework (INFO): Reject a block with a spend from a re-org'ed out tx\r\n> 2022-06-16T00:33:06.908000Z TestFramework (INFO): Reject a block with a spend from a re-org'ed out tx (on a forked chain)\r\n> 2022-06-16T00:33:07.227000Z TestFramework (INFO): Reject a block spending an immature coinbase.\r\n> 2022-06-16T00:33:07.440000Z TestFramework (INFO): Reject a block spending an immature coinbase (on a forked chain)\r\n> 2022-06-16T00:33:07.715000Z TestFramework (INFO): Accept a block of weight MAX_BLOCK_WEIGHT\r\n> 2022-06-16T00:33:07.983000Z TestFramework (INFO): Reject a block of weight MAX_BLOCK_WEIGHT + 4\r\n> 2022-06-16T00:33:08.378000Z TestFramework (INFO): Reject a block with coinbase input script size out of range\r\n> 2022-06-16T00:33:09.150000Z TestFramework (INFO): Accept a block with the max number of OP_CHECKMULTISIG sigops\r\n> 2022-06-16T00:33:09.277000Z TestFramework (INFO): Reject a block with too many OP_CHECKMULTISIG sigops\r\n> 2022-06-16T00:33:09.447000Z TestFramework (INFO): Accept a block with the max number of OP_CHECKMULTISIGVERIFY sigops\r\n> 2022-06-16T00:33:09.509000Z TestFramework (INFO): Reject a block with too many OP_CHECKMULTISIGVERIFY sigops\r\n> 2022-06-16T00:33:09.741000Z TestFramework (INFO): Accept a block with the max number of OP_CHECKSIGVERIFY sigops\r\n> 2022-06-16T00:33:09.818000Z TestFramework (INFO): Reject a block with too many OP_CHECKSIGVERIFY sigops\r\n> 2022-06-16T00:33:10.069000Z TestFramework (INFO): Reject a block spending transaction from a block which failed to connect\r\n> 2022-06-16T00:33:10.434000Z TestFramework (INFO): Check P2SH SIGOPS are correctly counted\r\n> 2022-06-16T00:33:18.330000Z TestFramework (INFO): Reject a block with too many P2SH sigops\r\n> 2022-06-16T00:33:57.687000Z TestFramework (INFO): Accept a block with the max number of P2SH sigops\r\n> 2022-06-16T00:34:01.161000Z TestFramework (INFO): Build block 44 manually\r\n> 2022-06-16T00:34:01.182000Z TestFramework (INFO): Reject a block with a non-coinbase as the first tx\r\n> 2022-06-16T00:34:01.393000Z TestFramework (INFO): Reject a block with no transactions\r\n> 2022-06-16T00:34:01.605000Z TestFramework (INFO): Reject a block with invalid work\r\n> 2022-06-16T00:34:01.835000Z TestFramework (INFO): Reject a block with a timestamp >2 hours in the future\r\n> 2022-06-16T00:34:01.897000Z TestFramework (INFO): Reject a block with invalid merkle hash\r\n> 2022-06-16T00:34:02.059000Z TestFramework (INFO): Reject a block with incorrect POW limit\r\n> 2022-06-16T00:34:02.271000Z TestFramework (INFO): Reject a block with two coinbase transactions\r\n> 2022-06-16T00:34:02.478000Z TestFramework (INFO): Reject a block with duplicate transactions\r\n> 2022-06-16T00:34:02.800000Z TestFramework (INFO): Reject a block with timestamp before MedianTimePast\r\n> 2022-06-16T00:34:03.020000Z TestFramework (INFO): Accept a previously rejected future block at a later time\r\n> 2022-06-16T00:34:03.150000Z TestFramework (INFO): Reject a block with a duplicate transaction in the Merkle Tree (but with a valid Merkle Root)\r\n> 2022-06-16T00:34:03.371000Z TestFramework (INFO): Reject a block with two duplicate transactions in the Merkle Tree (but with a valid Merkle Root)\r\n> 2022-06-16T00:34:03.797000Z TestFramework (INFO): Reject a block with a transaction with prevout.n out of range\r\n> 2022-06-16T00:34:04.011000Z TestFramework (INFO): Reject a block with a transaction with outputs > inputs\r\n> 2022-06-16T00:34:04.325000Z TestFramework (INFO): Reject a block with a transaction with a duplicate hash of a previous transaction (BIP30)\r\n> 2022-06-16T00:34:04.656000Z TestFramework (INFO): Reject a block with a transaction with a nonfinal locktime\r\n> 2022-06-16T00:34:04.865000Z TestFramework (INFO): Reject a block with a coinbase transaction with a nonfinal locktime\r\n> 2022-06-16T00:34:05.073000Z TestFramework (INFO): Accept a valid block even if a bloated version of the block has previously been sent\r\n> 2022-06-16T00:34:05.450000Z TestFramework (INFO): Accept a block with a transaction spending an output created in the same block\r\n> 2022-06-16T00:34:05.558000Z TestFramework (INFO): Reject a block with a transaction spending an output created later in the same block\r\n> 2022-06-16T00:34:05.773000Z TestFramework (INFO): Reject a block with a transaction double spending a transaction created in the same block\r\n> 2022-06-16T00:34:05.991000Z TestFramework (INFO): Reject a block trying to claim too much subsidy in the coinbase transaction\r\n> 2022-06-16T00:34:06.204000Z TestFramework (INFO): Accept a block claiming the correct subsidy in the coinbase transaction\r\n> 2022-06-16T00:34:06.310000Z TestFramework (INFO): Reject a block containing a transaction spending from a non-existent input\r\n> 2022-06-16T00:34:06.523000Z TestFramework (INFO): Reject a block containing a duplicate transaction but with the same Merkle root (Merkle tree malleability\r\n> 2022-06-16T00:34:06.857000Z TestFramework (INFO): Reject a block containing too many sigops after a large script element\r\n> 2022-06-16T00:34:07.248000Z TestFramework (INFO): Check sigops are counted correctly after an invalid script element\r\n> 2022-06-16T00:34:07.732000Z TestFramework (INFO): Test transaction resurrection during a re-org\r\n> 2022-06-16T00:34:08.332000Z TestFramework (INFO): Accept a block with invalid opcodes in dead execution paths\r\n> 2022-06-16T00:34:08.450000Z TestFramework (INFO): Test re-orging blocks with OP_RETURN in them\r\n> 2022-06-16T00:34:09.177000Z TestFramework (INFO): Test a re-org of one week's worth of blocks (1088 blocks)\r\n> \r\n> \r\n> stderr:\r\n\r\n\r\n\r\n\r\n\r\n> 21/245 - feature_pruning.py failed, Duration: 582 s\r\n\r\n    \r\n\r\n> stdout:\r\n> 2022-06-16T00:28:16.191000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20220615_202813/feature_pruning_244\r\n> 2022-06-16T00:28:29.460000Z TestFramework (INFO): Warning! This test requires 4GB of disk space\r\n> 2022-06-16T00:28:29.502000Z TestFramework (INFO): Mining a big blockchain of 995 blocks\r\n> 2022-06-16T00:33:30.483000Z TestFramework (INFO): Check that we haven't started pruning yet because we're below PruneAfterHeight\r\n> 2022-06-16T00:33:30.605000Z TestFramework (INFO): Success\r\n> 2022-06-16T00:33:30.617000Z TestFramework (INFO): Though we're already using more than 550MiB, current usage: 592.1861438751221\r\n> 2022-06-16T00:33:30.617000Z TestFramework (INFO): Mining 25 more blocks should cause the first block file to be pruned\r\n> 2022-06-16T00:33:39.588000Z TestFramework (INFO): Success\r\n> 2022-06-16T00:33:39.589000Z TestFramework (INFO): Usage should be below target: 480.31389808654785\r\n> 2022-06-16T00:33:39.592000Z TestFramework (INFO): Check that we'll exceed disk space target if we have a very high stale block rate\r\n> 2022-06-16T00:33:39.597000Z TestFramework (INFO): Mine 24 (stale) blocks on Node 1, followed by 25 (main chain) block reorg from Node 0, for 12 rounds\r\n> 2022-06-16T00:35:52.780000Z TestFramework (INFO): Usage can be over target because of high stale rate: 512.3138980865479\r\n> 2022-06-16T00:35:52.845000Z TestFramework (INFO): Check that we can survive a 288 block reorg still\r\n> 2022-06-16T00:35:52.849000Z TestFramework (INFO): Current block height: 1320\r\n> 2022-06-16T00:35:52.850000Z TestFramework (INFO): Invalidating block 44af5766f16112c8b04c19385700828e5ac236f42808804330eaf46e1312f4fb at height 1033\r\n> 2022-06-16T00:35:57.785000Z TestFramework (INFO): New best height: 1032\r\n> 2022-06-16T00:35:57.901000Z TestFramework (INFO): Generating new longer chain of 300 more blocks\r\n> 2022-06-16T00:35:59.900000Z TestFramework (INFO): Reconnect nodes\r\n> 2022-06-16T00:37:25.231000Z TestFramework (ERROR): JSONRPC error\r\n> Traceback (most recent call last):\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 166, in _get_response\r\n>     http_response = self.__conn.getresponse()\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1347, in getresponse\r\n>     response.begin()\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 307, in begin\r\n>     version, status, reason = self._read_status()\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 268, in _read_status\r\n>     line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\r\n>   File \"/usr/lib/python3.9/socket.py\", line 704, in readinto\r\n>     return self._sock.recv_into(b)\r\n> socket.timeout: timed out\r\n> \r\n> During handling of the above exception, another exception occurred:\r\n> \r\n> Traceback (most recent call last):\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 133, in main\r\n>     self.run_test()\r\n>   File \"/home/user/bitcoin/test/functional/feature_pruning.py\", line 418, in run_test\r\n>     self.reorg_test()  # (1033, )\r\n>   File \"/home/user/bitcoin/test/functional/feature_pruning.py\", line 217, in reorg_test\r\n>     self.sync_blocks(self.nodes[0:3], timeout=120)\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 676, in sync_blocks\r\n>     best_hash = [x.getbestblockhash() for x in rpc_connections]\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 676, in <listcomp>\r\n>     best_hash = [x.getbestblockhash() for x in rpc_connections]\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/coverage.py\", line 49, in __call__\r\n>     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 142, in __call__\r\n>     response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 108, in _request\r\n>     return self._get_response()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 168, in _get_response\r\n>     raise JSONRPCException({\r\n> test_framework.authproxy.JSONRPCException: 'getbestblockhash' RPC took longer than 60.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)\r\n> 2022-06-16T00:37:50.789000Z TestFramework (INFO): Stopping nodes\r\n> 2022-06-16T00:37:50.808000Z TestFramework.node0 (ERROR): Unable to stop node.\r\n> Traceback (most recent call last):\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_node.py\", line 336, in stop_node\r\n>     self.stop(wait=wait)\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/coverage.py\", line 49, in __call__\r\n>     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 142, in __call__\r\n>     response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 107, in _request\r\n>     self.__conn.request(method, path, postdata, headers)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1255, in request\r\n>     self._send_request(method, url, body, headers, encode_chunked)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1266, in _send_request\r\n>     self.putrequest(method, url, **skips)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1092, in putrequest\r\n>     raise CannotSendRequest(self.__state)\r\n> http.client.CannotSendRequest: Request-sent\r\n> [node 5] Cleaning up leftover process\r\n> [node 2] Cleaning up leftover process\r\n> [node 1] Cleaning up leftover process\r\n> [node 0] Cleaning up leftover process\r\n> \r\n> \r\n> stderr:\r\n> Traceback (most recent call last):\r\n>   File \"/home/user/bitcoin/test/functional/feature_pruning.py\", line 486, in <module>\r\n>     PruneTest().main()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 156, in main\r\n>     exit_code = self.shutdown()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 311, in shutdown\r\n>     self.stop_nodes()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 571, in stop_nodes\r\n>     node.wait_until_stopped()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_node.py\", line 382, in wait_until_stopped\r\n>     wait_until_helper(self.is_node_stopped, timeout=timeout, timeout_factor=self.timeout_factor)\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/util.py\", line 265, in wait_until_helper\r\n>     if predicate():\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_node.py\", line 372, in is_node_stopped\r\n>     assert return_code == 0, self._node_msg(\r\n> AssertionError: [node 0] Node returned non-zero exit code (-9) when stopping\r\n\r\n\r\n\r\n\r\n\r\n\r\n> 245/245 - feature_dbcrash.py failed, Duration: 2812 s\r\n\r\n                  \r\n\r\n> stdout:\r\n> 2022-06-16T00:28:16.295000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20220615_202813/feature_dbcrash_243\r\n> 2022-06-16T00:28:46.954000Z TestFramework (INFO): Prepped 5000 utxo entries\r\n> 2022-06-16T00:28:50.396000Z TestFramework (INFO): Iteration 0, generating 2500 transactions [0, 0, 0]\r\n> 2022-06-16T00:31:57.072000Z TestFramework (INFO): Iteration 1, generating 2500 transactions [0, 0, 0]\r\n> 2022-06-16T00:34:58.594000Z TestFramework (INFO): Iteration 2, generating 2500 transactions [0, 0, 0]\r\n> 2022-06-16T00:38:52.851000Z TestFramework (INFO): Iteration 3, generating 2500 transactions [0, 0, 0]\r\n> 2022-06-16T00:40:32.251000Z TestFramework (INFO): Iteration 4, generating 2500 transactions [0, 0, 0]\r\n> 2022-06-16T00:42:39.525000Z TestFramework (INFO): Iteration 5, generating 2500 transactions [0, 0, 0]\r\n> 2022-06-16T00:47:05.828000Z TestFramework (INFO): Iteration 6, generating 2500 transactions [0, 0, 0]\r\n> 2022-06-16T00:48:43.793000Z TestFramework (INFO): Iteration 7, generating 2500 transactions [1, 1, 0]\r\n> 2022-06-16T00:50:17.816000Z TestFramework (INFO): Iteration 8, generating 2500 transactions [2, 1, 0]\r\n> 2022-06-16T00:51:41.498000Z TestFramework (INFO): Iteration 9, generating 2500 transactions [3, 1, 0]\r\n> 2022-06-16T00:52:50.168000Z TestFramework (INFO): Iteration 10, generating 2500 transactions [4, 1, 0]\r\n> 2022-06-16T00:53:23.849000Z TestFramework (INFO): Iteration 11, generating 2500 transactions [4, 1, 0]\r\n> 2022-06-16T00:54:00.627000Z TestFramework (INFO): Iteration 12, generating 2500 transactions [4, 1, 0]\r\n> 2022-06-16T00:54:38.547000Z TestFramework (INFO): Iteration 13, generating 2500 transactions [4, 1, 0]\r\n> 2022-06-16T00:55:19.742000Z TestFramework (INFO): Iteration 14, generating 2500 transactions [5, 2, 0]\r\n> 2022-06-16T00:55:58.554000Z TestFramework (INFO): Iteration 15, generating 2500 transactions [5, 2, 0]\r\n> 2022-06-16T00:56:40.740000Z TestFramework (INFO): Iteration 16, generating 2500 transactions [5, 3, 0]\r\n> 2022-06-16T00:57:20.679000Z TestFramework (INFO): Iteration 17, generating 2500 transactions [6, 3, 0]\r\n> 2022-06-16T00:57:59.576000Z TestFramework (INFO): Iteration 18, generating 2500 transactions [6, 3, 0]\r\n> 2022-06-16T00:58:38.372000Z TestFramework (INFO): Iteration 19, generating 2500 transactions [6, 3, 0]\r\n> 2022-06-16T00:59:17.384000Z TestFramework (INFO): Iteration 20, generating 2500 transactions [6, 3, 0]\r\n> 2022-06-16T00:59:56.572000Z TestFramework (INFO): Iteration 21, generating 2500 transactions [6, 3, 0]\r\n> 2022-06-16T01:00:38.183000Z TestFramework (INFO): Iteration 22, generating 2500 transactions [6, 4, 0]\r\n> 2022-06-16T01:01:19.304000Z TestFramework (INFO): Iteration 23, generating 2500 transactions [7, 4, 0]\r\n> 2022-06-16T01:02:01.291000Z TestFramework (INFO): Iteration 24, generating 2500 transactions [7, 5, 0]\r\n> 2022-06-16T01:02:44.272000Z TestFramework (INFO): Iteration 25, generating 2500 transactions [7, 5, 0]\r\n> 2022-06-16T01:03:30.375000Z TestFramework (INFO): Iteration 26, generating 2500 transactions [8, 6, 0]\r\n> 2022-06-16T01:04:14.778000Z TestFramework (INFO): Iteration 27, generating 2500 transactions [8, 6, 0]\r\n> 2022-06-16T01:05:05.355000Z TestFramework (INFO): Iteration 28, generating 2500 transactions [9, 7, 0]\r\n> 2022-06-16T01:05:49.274000Z TestFramework (INFO): Iteration 29, generating 2500 transactions [9, 7, 0]\r\n> 2022-06-16T01:06:36.106000Z TestFramework (INFO): Iteration 30, generating 2500 transactions [9, 7, 0]\r\n> 2022-06-16T01:07:23.495000Z TestFramework (INFO): Iteration 31, generating 2500 transactions [10, 7, 0]\r\n> 2022-06-16T01:08:13.103000Z TestFramework (INFO): Iteration 32, generating 2500 transactions [10, 8, 0]\r\n> 2022-06-16T01:09:02.471000Z TestFramework (INFO): Iteration 33, generating 2500 transactions [10, 8, 0]\r\n> 2022-06-16T01:09:54.083000Z TestFramework (INFO): Iteration 34, generating 2500 transactions [11, 8, 0]\r\n> 2022-06-16T01:10:46.416000Z TestFramework (INFO): Iteration 35, generating 2500 transactions [12, 8, 0]\r\n> 2022-06-16T01:11:35.339000Z TestFramework (INFO): Iteration 36, generating 2500 transactions [12, 8, 0]\r\n> 2022-06-16T01:12:24.634000Z TestFramework (INFO): Iteration 37, generating 2500 transactions [12, 8, 0]\r\n> 2022-06-16T01:13:19.854000Z TestFramework (INFO): Iteration 38, generating 2500 transactions [12, 8, 0]\r\n> 2022-06-16T01:14:13.032000Z TestFramework (INFO): Iteration 39, generating 2500 transactions [12, 8, 0]\r\n> 2022-06-16T01:15:00.597000Z TestFramework (ERROR): Unexpected exception caught during testing\r\n> Traceback (most recent call last):\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 108, in _request\r\n>     return self._get_response()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 166, in _get_response\r\n>     http_response = self.__conn.getresponse()\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1347, in getresponse\r\n>     response.begin()\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 307, in begin\r\n>     version, status, reason = self._read_status()\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 276, in _read_status\r\n>     raise RemoteDisconnected(\"Remote end closed connection without\"\r\n> http.client.RemoteDisconnected: Remote end closed connection without response\r\n> \r\n> During handling of the above exception, another exception occurred:\r\n> \r\n> Traceback (most recent call last):\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 133, in main\r\n>     self.run_test()\r\n>   File \"/home/user/bitcoin/test/functional/feature_dbcrash.py\", line 263, in run_test\r\n>     self.wallet.rescan_utxos()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/wallet.py\", line 106, in rescan_utxos\r\n>     res = self._test_node.scantxoutset(action=\"start\", scanobjects=[self.get_descriptor()])\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/coverage.py\", line 49, in __call__\r\n>     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 142, in __call__\r\n>     response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 113, in _request\r\n>     self.__conn.request(method, path, postdata, headers)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1255, in request\r\n>     self._send_request(method, url, body, headers, encode_chunked)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1301, in _send_request\r\n>     self.endheaders(body, encode_chunked=encode_chunked)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1250, in endheaders\r\n>     self._send_output(message_body, encode_chunked=encode_chunked)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1010, in _send_output\r\n>     self.send(msg)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 950, in send\r\n>     self.connect()\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 921, in connect\r\n>     self.sock = self._create_connection(\r\n>   File \"/usr/lib/python3.9/socket.py\", line 843, in create_connection\r\n>     raise err\r\n>   File \"/usr/lib/python3.9/socket.py\", line 831, in create_connection\r\n>     sock.connect(sa)\r\n> ConnectionRefusedError: [Errno 111] Connection refused\r\n> 2022-06-16T01:15:05.618000Z TestFramework (INFO): Stopping nodes\r\n> 2022-06-16T01:15:05.743000Z TestFramework.node3 (ERROR): Unable to stop node.\r\n> Traceback (most recent call last):\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_node.py\", line 336, in stop_node\r\n>     self.stop(wait=wait)\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/coverage.py\", line 49, in __call__\r\n>     return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 142, in __call__\r\n>     response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/authproxy.py\", line 107, in _request\r\n>     self.__conn.request(method, path, postdata, headers)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1255, in request\r\n>     self._send_request(method, url, body, headers, encode_chunked)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1266, in _send_request\r\n>     self.putrequest(method, url, **skips)\r\n>   File \"/usr/lib/python3.9/http/client.py\", line 1092, in putrequest\r\n>     raise CannotSendRequest(self.__state)\r\n> http.client.CannotSendRequest: Request-sent\r\n> [node 3] Cleaning up leftover process\r\n> \r\n> \r\n> stderr:\r\n> Traceback (most recent call last):\r\n>   File \"/home/user/bitcoin/test/functional/feature_dbcrash.py\", line 288, in <module>\r\n>     ChainstateWriteCrashTest().main()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 156, in main\r\n>     exit_code = self.shutdown()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 311, in shutdown\r\n>     self.stop_nodes()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_framework.py\", line 571, in stop_nodes\r\n>     node.wait_until_stopped()\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_node.py\", line 382, in wait_until_stopped\r\n>     wait_until_helper(self.is_node_stopped, timeout=timeout, timeout_factor=self.timeout_factor)\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/util.py\", line 265, in wait_until_helper\r\n>     if predicate():\r\n>   File \"/home/user/bitcoin/test/functional/test_framework/test_node.py\", line 372, in is_node_stopped\r\n>     assert return_code == 0, self._node_msg(\r\n> AssertionError: [node 3] Node returned non-zero exit code (-9) when stopping\r\n\r\n\r\n\r\nTry failed tests individually:\r\n\r\n\r\n\r\nuser@localhost:~/bitcoin/test/functional$ `python3 feature_block.py`\r\n\r\n> ...\r\n> ...\r\n> 2022-06-16T01:48:03.457000Z TestFramework (INFO): Test re-orging blocks with OP_RETURN in them\r\n> 2022-06-16T01:48:04.208000Z TestFramework (INFO): Test a re-org of one week's worth of blocks (1088 blocks)\r\n> Killed\r\n\r\nI didn't terminate, not sure why this was killed.\r\n\r\n\r\nuser@localhost:~/bitcoin/test/functional$ `python3 feature_dbcrash.py`\r\n\r\n> ...\r\n> ...\r\n> 2022-06-16T02:22:04.399000Z TestFramework (INFO): Iteration 39, generating 2500 transactions [14, 6, 5]\r\n> 2022-06-16T02:22:45.148000Z TestFramework (INFO): Verifying utxo hash matches for all nodes\r\n> 2022-06-16T02:22:45.611000Z TestFramework (INFO): Restarted nodes: [14, 6, 5]; crashes on restart: 19\r\n> 2022-06-16T02:22:45.735000Z TestFramework (INFO): Stopping nodes\r\n> 2022-06-16T02:22:46.082000Z TestFramework (INFO): Cleaning up /tmp/bitcoin_func_test_dlvz7p5v on exit\r\n> 2022-06-16T02:22:46.084000Z TestFramework (INFO): Tests successful\r\n\r\nThis succeeds when tested individually\r\n\r\n\r\n\r\n\r\nuser@localhost:~/bitcoin/test/functional$ `python3 feature_pruning.py`\r\n\r\n> ...\r\n> ...\r\n> 2022-06-16T02:30:49.127000Z TestFramework (INFO): Done\r\n> 2022-06-16T02:30:49.208000Z TestFramework (INFO): Stopping nodes\r\n> 2022-06-16T02:30:49.584000Z TestFramework (INFO): Cleaning up /tmp/bitcoin_func_test_l2tv3kpn on exit\r\n> 2022-06-16T02:30:49.584000Z TestFramework (INFO): Tests successful\r\n\r\nThis also succeeds\r\n\r\n\r\n\r\nuser@localhost:~/bitcoin/test/util$ `python3 test_runner.py`\r\n\r\nSuccessful\r\n\r\n`bitcoin-qt` opens as expected\r\n\r\nMachine details:\r\n\r\nQubes 4.1\r\nUp to date Debian 11 Standard VM\r\nCoreboot 4.14\r\nx86\r\n",
    "user": {
      "login": "Rspigler",
      "id": 24482484,
      "node_id": "MDQ6VXNlcjI0NDgyNDg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/24482484?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Rspigler",
      "html_url": "https://github.com/Rspigler",
      "followers_url": "https://api.github.com/users/Rspigler/followers",
      "following_url": "https://api.github.com/users/Rspigler/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/Rspigler/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/Rspigler/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/Rspigler/subscriptions",
      "organizations_url": "https://api.github.com/users/Rspigler/orgs",
      "repos_url": "https://api.github.com/users/Rspigler/repos",
      "events_url": "https://api.github.com/users/Rspigler/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/Rspigler/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 477890092,
        "node_id": "MDU6TGFiZWw0Nzc4OTAwOTI=",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Questions%20and%20Help",
        "name": "Questions and Help",
        "color": "006688",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "locked": false,
    "comments": 3,
    "closed_at": "2022-06-19T00:12:58Z",
    "created_at": "2022-06-16T03:12:57Z",
    "updated_at": "2022-06-19T00:12:58Z"
  },
  "events": [
    {
      "event": "commented",
      "id": 1157243200,
      "node_id": "IC_kwDOABII585E-iFA",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1157243200",
      "actor": {
        "login": "MarcoFalke",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarcoFalke",
        "html_url": "https://github.com/MarcoFalke",
        "followers_url": "https://api.github.com/users/MarcoFalke/followers",
        "following_url": "https://api.github.com/users/MarcoFalke/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/MarcoFalke/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/MarcoFalke/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
        "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
        "repos_url": "https://api.github.com/users/MarcoFalke/repos",
        "events_url": "https://api.github.com/users/MarcoFalke/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-06-16T05:18:28Z",
      "updated_at": "2022-06-16T05:18:28Z",
      "author_association": "MEMBER",
      "body": "Looks like OOM in the linker. What is the available memory? `free -h`",
      "user": {
        "login": "MarcoFalke",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarcoFalke",
        "html_url": "https://github.com/MarcoFalke",
        "followers_url": "https://api.github.com/users/MarcoFalke/followers",
        "following_url": "https://api.github.com/users/MarcoFalke/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/MarcoFalke/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/MarcoFalke/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
        "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
        "repos_url": "https://api.github.com/users/MarcoFalke/repos",
        "events_url": "https://api.github.com/users/MarcoFalke/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/25385#issuecomment-1157243200",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/25385"
    },
    {
      "event": "commented",
      "id": 1158688714,
      "node_id": "IC_kwDOABII585FEC_K",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1158688714",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-06-17T09:30:12Z",
      "updated_at": "2022-06-17T09:30:12Z",
      "author_association": "MEMBER",
      "body": "> fatal error: ld terminated with signal 9\r\n\r\nYes this is a local resources issue.\r\n\r\n> /bin/bash: line 2: test/test_bitcoin: Permission denied\r\n\r\nAlso a local issue.",
      "user": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/25385#issuecomment-1158688714",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/25385"
    },
    {
      "event": "labeled",
      "id": 6827890194,
      "node_id": "LE_lADOABII585L4EIxzwAAAAGW-VYS",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/6827890194",
      "actor": {
        "login": "MarcoFalke",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MarcoFalke",
        "html_url": "https://github.com/MarcoFalke",
        "followers_url": "https://api.github.com/users/MarcoFalke/followers",
        "following_url": "https://api.github.com/users/MarcoFalke/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/MarcoFalke/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/MarcoFalke/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/MarcoFalke/subscriptions",
        "organizations_url": "https://api.github.com/users/MarcoFalke/orgs",
        "repos_url": "https://api.github.com/users/MarcoFalke/repos",
        "events_url": "https://api.github.com/users/MarcoFalke/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/MarcoFalke/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-06-17T10:24:07Z",
      "label": {
        "name": "Questions and Help",
        "color": "006688"
      }
    },
    {
      "event": "commented",
      "id": 1159586655,
      "node_id": "IC_kwDOABII585FHeNf",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1159586655",
      "actor": {
        "login": "Rspigler",
        "id": 24482484,
        "node_id": "MDQ6VXNlcjI0NDgyNDg0",
        "avatar_url": "https://avatars.githubusercontent.com/u/24482484?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Rspigler",
        "html_url": "https://github.com/Rspigler",
        "followers_url": "https://api.github.com/users/Rspigler/followers",
        "following_url": "https://api.github.com/users/Rspigler/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/Rspigler/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/Rspigler/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/Rspigler/subscriptions",
        "organizations_url": "https://api.github.com/users/Rspigler/orgs",
        "repos_url": "https://api.github.com/users/Rspigler/repos",
        "events_url": "https://api.github.com/users/Rspigler/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/Rspigler/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-06-19T00:12:58Z",
      "updated_at": "2022-06-19T00:12:58Z",
      "author_association": "CONTRIBUTOR",
      "body": "Ah my apologies. I thought it was a memory issue - I had paused my other qubes and allocated more memory towards it. I guess I just needed to restart and shut some other qubes down.  Sorry",
      "user": {
        "login": "Rspigler",
        "id": 24482484,
        "node_id": "MDQ6VXNlcjI0NDgyNDg0",
        "avatar_url": "https://avatars.githubusercontent.com/u/24482484?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Rspigler",
        "html_url": "https://github.com/Rspigler",
        "followers_url": "https://api.github.com/users/Rspigler/followers",
        "following_url": "https://api.github.com/users/Rspigler/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/Rspigler/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/Rspigler/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/Rspigler/subscriptions",
        "organizations_url": "https://api.github.com/users/Rspigler/orgs",
        "repos_url": "https://api.github.com/users/Rspigler/repos",
        "events_url": "https://api.github.com/users/Rspigler/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/Rspigler/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/25385#issuecomment-1159586655",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/25385"
    },
    {
      "event": "closed",
      "id": 6834084907,
      "node_id": "CE_lADOABII585L4EIxzwAAAAGXV9wr",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/6834084907",
      "actor": {
        "login": "Rspigler",
        "id": 24482484,
        "node_id": "MDQ6VXNlcjI0NDgyNDg0",
        "avatar_url": "https://avatars.githubusercontent.com/u/24482484?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Rspigler",
        "html_url": "https://github.com/Rspigler",
        "followers_url": "https://api.github.com/users/Rspigler/followers",
        "following_url": "https://api.github.com/users/Rspigler/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/Rspigler/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/Rspigler/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/Rspigler/subscriptions",
        "organizations_url": "https://api.github.com/users/Rspigler/orgs",
        "repos_url": "https://api.github.com/users/Rspigler/repos",
        "events_url": "https://api.github.com/users/Rspigler/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/Rspigler/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2022-06-19T00:12:58Z"
    }
  ]
}